package com.company.notexpress;

import androidx.room.Entity;
import androidx.room.PrimaryKey;

@Entity(tableName = "note_table") // through this annotation we enable the room database to write the necessary codein the background
public class Note {

    @PrimaryKey(autoGenerate = true)
    public int id;  // id is the primary key and the values will be autogenerated

    public String title;

    public String description;
    //the room database automatically creates fields with the above variables defined


    public Note(String title, String description) { // we do not choose 'id' bcoz it will be generated automatically
        this.title = title;
        this.description = description;
    }

    public int getId() {
        return id;
    }

    public String getTitle() {
        return title;
    }

    public String getDescription() {
        return description;
    }

    public void setId(int id) {
        this.id = id;
    }
}
